#!python

import os
import platform
import subprocess

AddOption('--prefix',
          dest='prefix',
          type='string',
          nargs=1,
          action='store',
          metavar='DIR',
          help='installation prefix')
env = Environment(PREFIX = GetOption('prefix'))
prefix = GetOption('prefix')
base = os.path.abspath(os.path.join(prefix,os.pardir))
base = os.path.join(base,'work')
sourcePath = os.path.join(base,'source')
binPath = os.path.join(prefix,'bin')

#if not platform.system()=='Linux':
env.Replace(CC = os.path.join(binPath,'gcc'))
    
env.Append(CCFLAGS = ['-static','-ffloat-store','-O3','-DVerbOpt',
'-g', '-Wall', '-O0'])
env.Append(LIBPATH = [os.path.join(sourcePath,'lib')])
env.Append(CPPPATH = [os.path.join(sourcePath,'include')])
env.Append(LIBS = ['tiff','geotiff','z','jpeg','lzma','m'])
GeoTiff2ENVI = env.Program(target='GeoTiff2ENVI', source=['GeoTiff2ENVI.c'])
env.Install(binPath, GeoTiff2ENVI)
env.Alias('install', binPath)