#!python

import os

base = os.path.join(os.sep,'Users','mschull','umdGD','pyDisALEXI')
sourcePath = os.path.join(base,'processData','source')
env = Environment(CC = 'gcc')
env.Append(CCFLAGS = ['-g','-O3'])
env.Append(LIBPATH = [os.path.join(sourcePath,'lib')])
env.Append(CPPPATH = [os.path.join(sourcePath,'include')])
#env.Append(LIBS = ['hdfeos','Gctp','mfhdf','df','sz','z','jpeg','m'])
env.Append(LIBS = ['Gctp','hdfeos','mfhdf','df','z','sz','jpeg','m'])

gapfillLAI = env.Program(target='gapfillLAI', source=['gapfillLAI.c'])

#DOES NOT WORK NOW
#env = Environment(F90 = 'gfortran')
#env.Append(F90FLAGS = ['-m32','-static'])
#env.Append(F90FLAGS = ['-static'])
#
#sources= ['basis.f90','fitgauss.f90','fitlogistic.f90','fungauss.f90',
#          'funlogistic.f90','gauss.f90','linlsq.f90','marquardt.f90',
#          'modweight.f90','median.f90','phenology.f90','savgol.f90',
#          'season.f90','spike.f90','timesatLAI.f90']
#          
#timesatLAI = env.Program(target='timesatLAI', source=sources)