#!python

import os
import platform
import subprocess


p = subprocess.Popen(["conda", "info", "--root"],stdout=subprocess.PIPE)
out = p.communicate()
condaPath = out[0][:-1]
base = os.path.abspath(os.path.join(os.getcwd(),os.pardir,os.pardir))
sourcePath = os.path.join(base,'source')
binPath = os.path.join(condaPath,'bin')
binPath = '$PREFIX/bin'

if not platform.system()=='Linux':
    env = Environment(CC = os.path.join(binPath,'gcc'))
else:
    env = Environment(CC = 'gcc')
env.Append(CCFLAGS = ['-static','-ffloat-store','-O3','-DVerbOpt',
'-g', '-Wall', '-O0'])
env.Append(LIBPATH = [os.path.join(sourcePath,'lib')])
env.Append(CPPPATH = [os.path.join(sourcePath,'include')])
env.Append(LIBS = ['m'])


sources = [	'global.c','xval.c','cubist.c','sort.c','construct.c',
           'predict.c','stats.c','discr.c','rules.c','contin.c',
           'formrules.c','formtree.c','getdata.c','getnames.c',
           'implicitatt.c','instance.c','modelfiles.c','prunetree.c',
           'regress.c','trees.c','update.c','utility.c']
Cubist = env.Program(target='cubist', source=sources)

env.Install(binPath, Cubist)
env.Alias('install', binPath)
